// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZsV0xrxlbTiIvgHtW6oZQrfCDaizCDU',
    appId: '1:319308871356:web:ae1790fddae8a9224942b9',
    messagingSenderId: '319308871356',
    projectId: 'expensetracker-885f3',
    authDomain: 'expensetracker-885f3.firebaseapp.com',
    storageBucket: 'expensetracker-885f3.firebasestorage.app',
    measurementId: 'G-JK55SFPMQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE4zQJ85ItHDVmznq8W39KlNDpoRaLz-4',
    appId: '1:319308871356:android:be9727952359c1ed4942b9',
    messagingSenderId: '319308871356',
    projectId: 'expensetracker-885f3',
    storageBucket: 'expensetracker-885f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYIn6l2mNwuH7OtjqwL-6sJiwFTF8mv_E',
    appId: '1:319308871356:ios:89a88a17a90fabb94942b9',
    messagingSenderId: '319308871356',
    projectId: 'expensetracker-885f3',
    storageBucket: 'expensetracker-885f3.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerWeek4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.expenseTrackerWeek4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}